
[[library]]
identifier = "tests"
name = "Tests"
paths = ["./tests"]
edit_enabled = true
create_enabled = false
snapshot_enabled = true
use_library_as_identifier_prefix = true
use_file_name_as_identifier = true
use_file_extension_as_format = true

[[library]]
identifier = "inbox"
name = "Inbox"
paths = ["./inbox"]
edit_enabled = true
create_enabled = true
create_name_timestamp_length = 3
create_name_random_length = 16
snapshot_enabled = true
use_library_as_identifier_prefix = false
use_file_name_as_identifier = true
use_file_extension_as_format = true

[globals]
terminal_enabled = true
xorg_enabled = true

[editor]
default_create_library = "inbox"
terminal_edit_command = ["nano", "--", "{{path}}"]
xorg_edit_command = ["howl", "--", "{{path}}"]
terminal_select_command = ["fzf", "--prompt", ": ", "-e", "-x", "-i"]
xorg_select_command = ["rofi", "-dmenu", "-p", "", "-i", "-no-custom"]

[server]
endpoint_ip = "127.9.212.148"
endpoint_port = 8080
edit_enabled = true
create_enabled = true

