
[[library]]
identifier = "tests"
name = "Tests"
paths = ["./tests"]
edit_enabled = true
create_enabled = false
snapshot_enabled = false
use_library_as_identifier_prefix = true
use_file_name_as_identifier = true
use_file_extension_as_format = true

[[library]]
identifier = "inbox"
name = "Inbox"
paths = ["./inbox"]
edit_enabled = true
create_enabled = true
create_name_timestamp_length = 3
create_name_random_length = 16
snapshot_enabled = true
use_library_as_identifier_prefix = false
use_file_name_as_identifier = true
use_file_extension_as_format = true

[[library]]
identifier = "imports"
name = "Imports"
paths = ["./imports"]
edit_enabled = false
create_enabled = false
snapshot_enabled = true
use_library_as_identifier_prefix = false
use_file_name_as_identifier = true
use_file_extension_as_format = true


[globals]
terminal_enabled = true
xorg_enabled = true

[editor]
default_create_library = "inbox"
terminal_edit_command = ["nano", "--", "{{path}}"]
xorg_edit_command = ["howl", "--", "{{path}}"]
terminal_select_command = ["fzf", "--prompt", ": ", "-e", "-x", "-i"]
xorg_select_command = ["rofi", "-dmenu", "-p", "", "-i", "-no-custom"]

[server]
endpoint_ip = "127.9.212.148"
endpoint_port = 8080
edit_enabled = true
create_enabled = true

[browser]
terminal_open_command = ["x-www", "guest:*", "open", "{{url}}"]
xorg_open_command = ["x-www", "guest:*", "open", "{{url}}"]


[[menu]]
identifier = "default"
label = "Default"
default = true
loop = true
commands = [
	
	{label = "edit / ...", command = "edit", arguments = ["--select"]},
	{label = "edit / tests", command = "edit", arguments = ["--library", "tests", "--select"]},
	{label = "edit / inbox", command = "edit", arguments = ["--library", "inbox", "--select"]},
	
	{label = "open / ...", command = "browse", arguments = ["--select"]},
	{label = "open / tests", command = "browse", arguments = ["--library", "tests", "--select"]},
	{label = "open / inbox", command = "browse", arguments = ["--library", "inbox", "--select"]},
	
	{label = "search / edit / ...", command = "search", arguments = ["--action", "edit", "--how", "body"]},
	{label = "search / edit / tests", command = "search", arguments = ["--library", "tests", "--action", "edit", "--how", "body"]},
	{label = "search / edit / inbox", command = "search", arguments = ["--library", "inbox", "--action", "edit", "--how", "body"]},
	
	{label = "search / open / ...", command = "search", arguments = ["--action", "browse", "--how", "body"]},
	{label = "search / open / tests", command = "search", arguments = ["--library", "tests", "--action", "browse", "--how", "body"]},
	{label = "search / open / inbox", command = "search", arguments = ["--library", "inbox", "--action", "browse", "--how", "body"]},
	
	{label = "create ->", command = "menu", arguments = ["--menu", "create"]},
]

[[menu]]
identifier = "create"
label = "Create"
commands = [
	{label = "create / ...", command = "create", arguments = ["--select"]},
	{label = "create / tests", command = "create", arguments = ["--library", "tests"]},
	{label = "create / inbox", command = "create", arguments = ["--library", "inbox"]},
]

